spring:
  profiles:
    active:
      -dev
---
server:
  port: 7001
spring:
  profiles: dev  
  application: 
    name: apmcloud-backend-config-dev
eureka:
  instance:
    hostname: apm-domain
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
