spring:
  profiles:
    active:
      -dev
---
server:
  port: 7001
spring:
  profiles: dev  
  application: 
    name: apmcloud-backend-config-dev
eureka:
  client:
    service-url:
      defaultZone: http://apm-domain:7001/eureka/
