spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev  
  application: 
    name: apmcloud-backend-config-dev
---
spring:
  profiles: prod   
  application: 
    name: apmcloud-backend-config-prod
