spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev  
  application: 
    name: apmcloud-backend-config-dev

foo: foo version 24

eureka:
  client:
    service-url:
      defaultZone: http://apm-domain:7001/eureka/
