spring:
  profiles:
    active:
      -dev
---
server:
  port: 8001
spring:
  profiles: dev  
  application: 
    name: apmcloud-backend-config-dev
eureka:
  instance:
    hostname: apm-domain
    instance-id: apm-cloud-sysadmin8001
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://apm-domain:7001/eureka/
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: org.apm.cloud.entities              # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                     # mapper映射文件
